emqx:
  username: "inchtek"
  password: "VC6bZaJXyhb"
  #qa3
#  server_port: 31883
#  server_address: "10.100.64.225"
#  api_username: "b70ee49583f63070"
#  api_password: "XerogOqcQUwd39AS8V43TWk4Sxs9C8oWHihW3t5YL03xF"
#  api_url: "https://emqx.qa2.inchtek.tech/api/v5/mqtt/topic_metrics"
  #qa4
  server_port: 31884
  server_address: "10.100.64.214"
  api_username: "e4bf2f2b0806872e"
  api_password: "oVy0MiL4UlAX9CRSRMdCBlOrFQ8TIuWB2RHOdBHhJG5P"
  api_url: "http://10.100.64.214:31084/api/v5/mqtt/topic_metrics"

kafka:
  #qa3
#  servers: "10.100.64.106:9094,10.100.64.107:9094,10.100.64.109:9094"
#  group_id:  "qa3-inchtek_driver_status_group"
#  partition: 0
#  topic: "qa3-inchtek_driver_status"
  #qa4
  servers: "10.100.64.94:9094,10.100.64.95:9094,10.100.64.96:9094"
  group_id:  "qa4-dev-inchtek_driver_status_group"
  partition: 0
  topic: "qa4-dev-inchtek_driver_status"

kafka2:
  #qa3
#  servers: "10.100.64.106:9094,10.100.64.107:9094,10.100.64.109:9094"
#  group_id:  "qa3-inchtek_driver_status_group"
#  partition: 0
#  topic: "qa3-inchtek_driver_status_detail"
  #qa4
  servers: "10.100.64.94:9094,10.100.64.95:9094,10.100.64.96:9094"
  group_id:  "qa4-dev-inchtek_driver_status_group"
  partition: 0
  topic: "qa4-dev-inchtek_driver_status_detail"

