k8s:
  enable: false

emqx:
  client_type: "emqx"
  username: "inchtek"
  password: "VC6bZaJXyhb"
  server_port: 1883
#  server_address: "emqx-test.seazonmotor.com"
  server_address: "10.100.64.74"
  api_key: "2d8de93560965eaa"
  api_secret: "oVi9AQROeCpjK5rjBAxjqDkKqOpmh9B6DrESZEj3FruRD"
  api_url: "http://10.100.64.74:18083/api/v5/metrics?aggregate=true"

kafka:
  client_type: "kafka"
  #qa3
  servers: "10.100.64.44:9092"
  group_id:  "qa2-inchtek_driver_status_group"
  partition: 0
#  topic: "test-full_network_parsing-vsoc"
#  topic: "test-full_network_parsing1-vsoc"
  topic: "dev-inchtek_driver_status"
#  topic: "dev-vsoc-inchtek_driver_status_detail_test"
#  topic: "dev-vsoc-vehicle-and-device-complete"
  offset: "earliest"
  #qa4

kafka2:
  client_type: "kafka"
  #qa3
  servers: "10.100.64.44:9092"
  group_id:  "qa2-inchtek_driver_status_group"
  partition: 0
  topic: "test-full_network_parsing_output-vsoc"
  #qa4
